# Generated by Django 4.2.13 on 2026-09-16 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educoredb_app', '0004_alter_customuser_id'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='sessionyearmodel',
            managers=[
            ],
        ),
    ]
